#!/bin/bash
python3 - << 'PYEOF'
import os

detector = open(os.path.expanduser("~/firewall/core/detector.py"), "w")
detector.write("#!/usr/bin/env python3\n")
detector.write("from collections import defaultdict\n")
detector.write("import time, logging, os, subprocess\n")
detector.write("\n")
detector.write("LOGS_PATH = os.path.join(os.path.dirname(__file__), '../logs/firewall.log')\n")
detector.write("logging.basicConfig(filename=LOGS_PATH, level=logging.INFO, format='%(asctime)s %(message)s')\n")
detector.write("\n")
detector.write("WHITELIST = {'192.168.64.1', '127.0.0.1'}\n")
detector.write("PORTSCAN_WINDOW = 10\n")
detector.write("PORTSCAN_THRESHOLD = 3\n")
detector.write("RATELIMIT_WINDOW = 5\n")
detector.write("RATELIMIT_THRESHOLD = 20\n")
detector.write("\n")
detector.write("port_tracker = defaultdict(list)\n")
detector.write("rate_tracker = defaultdict(list)\n")
detector.write("blocked_ips = set()\n")
detector.write("alerted_ips = set()\n")
detector.write("\n")
detector.write("def block_ip(src_ip, reason):\n")
detector.write("    if src_ip in blocked_ips or src_ip in WHITELIST: return\n")
detector.write("    blocked_ips.add(src_ip)\n")
detector.write("    subprocess.run(['sudo', 'iptables', '-A', 'INPUT', '-s', src_ip, '-j', 'DROP'], capture_output=True)\n")
detector.write("    msg = f'[BLOCK] IP {src_ip} bloqueada automaticamente por {reason}'\n")
detector.write("    print(msg)\n")
detector.write("    logging.warning(msg)\n")
detector.write("\n")
detector.write("def check_port_scan(src_ip, dst_port):\n")
detector.write("    if dst_port is None or src_ip in WHITELIST: return None\n")
detector.write("    now = time.time()\n")
detector.write("    port_tracker[src_ip] = [(ts, port) for ts, port in port_tracker[src_ip] if now - ts < PORTSCAN_WINDOW]\n")
detector.write("    port_tracker[src_ip].append((now, dst_port))\n")
detector.write("    unique_ports = set(p for _, p in port_tracker[src_ip])\n")
detector.write("    if len(unique_ports) >= PORTSCAN_THRESHOLD:\n")
detector.write("        if src_ip not in alerted_ips:\n")
detector.write("            alerted_ips.add(src_ip)\n")
detector.write("            msg = f'[WARNING] PORT SCAN detectado desde {src_ip} - {len(unique_ports)} puertos en {PORTSCAN_WINDOW}s: {sorted(unique_ports)}'\n")
detector.write("            print(msg)\n")
detector.write("            logging.warning(msg)\n")
detector.write("            block_ip(src_ip, 'PORT_SCAN')\n")
detector.write("            return 'PORT_SCAN'\n")
detector.write("    else:\n")
detector.write("        alerted_ips.discard(src_ip)\n")
detector.write("    return None\n")
detector.write("\n")
detector.write("def check_rate_limit(src_ip):\n")
detector.write("    if src_ip in WHITELIST: return None\n")
detector.write("    now = time.time()\n")
detector.write("    rate_tracker[src_ip] = [ts for ts in rate_tracker[src_ip] if now - ts < RATELIMIT_WINDOW]\n")
detector.write("    rate_tracker[src_ip].append(now)\n")
detector.write("    count = len(rate_tracker[src_ip])\n")
detector.write("    if count >= RATELIMIT_THRESHOLD:\n")
detector.write("        msg = f'[WARNING] RATE LIMIT excedido desde {src_ip} - {count} paquetes en {RATELIMIT_WINDOW}s'\n")
detector.write("        print(msg)\n")
detector.write("        logging.warning(msg)\n")
detector.write("        block_ip(src_ip, 'RATE_LIMIT')\n")
detector.write("        return 'RATE_LIMIT'\n")
detector.write("    return None\n")
detector.write("\n")
detector.write("def analyze(src_ip, dst_port):\n")
detector.write("    alerts = []\n")
detector.write("    r1 = check_port_scan(src_ip, dst_port)\n")
detector.write("    if r1: alerts.append(r1)\n")
detector.write("    r2 = check_rate_limit(src_ip)\n")
detector.write("    if r2: alerts.append(r2)\n")
detector.write("    return alerts\n")
detector.write("\n")
detector.write("def get_blocked_ips():\n")
detector.write("    return list(blocked_ips)\n")
detector.close()
print("detector.py corregido OK")
PYEOF
