#!/bin/bash
python3 - << 'PYEOF'
import os

ai = open(os.path.expanduser("~/firewall/core/ai_analyzer.py"), "w")
ai.write("#!/usr/bin/env python3\n")
ai.write("import urllib.request, json, os, threading\n")
ai.write("\n")
ai.write("API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')\n")
ai.write("API_URL = 'https://api.anthropic.com/v1/messages'\n")
ai.write("\n")
ai.write("def analyze_threat(src_ip, alert_type, details):\n")
ai.write("    if not API_KEY:\n")
ai.write("        return 'API key no configurada'\n")
ai.write("    prompt = f'Eres un analista de ciberseguridad. Analiza esta alerta en 2-3 frases en espanol:\\n'\n")
ai.write("    prompt += f'IP origen: {src_ip}\\n'\n")
ai.write("    prompt += f'Tipo de alerta: {alert_type}\\n'\n")
ai.write("    prompt += f'Detalles: {details}\\n'\n")
ai.write("    prompt += 'Explica el riesgo y da una recomendacion concreta.'\n")
ai.write("    payload = json.dumps({\n")
ai.write("        'model': 'claude-haiku-4-5',\n")
ai.write("        'max_tokens': 200,\n")
ai.write("        'messages': [{'role': 'user', 'content': prompt}]\n")
ai.write("    }).encode('utf-8')\n")
ai.write("    req = urllib.request.Request(API_URL, data=payload, method='POST')\n")
ai.write("    req.add_header('Content-Type', 'application/json')\n")
ai.write("    req.add_header('x-api-key', API_KEY)\n")
ai.write("    req.add_header('anthropic-version', '2023-06-01')\n")
ai.write("    try:\n")
ai.write("        with urllib.request.urlopen(req, timeout=15) as resp:\n")
ai.write("            data = json.loads(resp.read().decode('utf-8'))\n")
ai.write("            return data['content'][0]['text']\n")
ai.write("    except urllib.request.HTTPError as e:\n")
ai.write("        body = e.read().decode('utf-8')\n")
ai.write("        return f'Error HTTP {e.code}: {body[:100]}'\n")
ai.write("    except Exception as e:\n")
ai.write("        return f'Error: {str(e)}'\n")
ai.write("\n")
ai.write("def analyze_async(src_ip, alert_type, details, callback):\n")
ai.write("    def run():\n")
ai.write("        result = analyze_threat(src_ip, alert_type, details)\n")
ai.write("        callback(result)\n")
ai.write("    t = threading.Thread(target=run, daemon=True)\n")
ai.write("    t.start()\n")
ai.close()
print("ai_analyzer.py corregido OK")
PYEOF
