#!/bin/bash
python3 - << 'PYEOF'
import os

os.makedirs(os.path.expanduser("~/firewall/dashboard/templates"), exist_ok=True)

app = open(os.path.expanduser("~/firewall/dashboard/app.py"), "w")
app.write("#!/usr/bin/env python3\n")
app.write("from flask import Flask, render_template, jsonify\n")
app.write("from flask_socketio import SocketIO\n")
app.write("import json, os, threading, subprocess, re, time\n")
app.write("import sys\n")
app.write("sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../core'))\n")
app.write("from detector import analyze, get_blocked_ips\n")
app.write("\n")
app.write("app = Flask(__name__)\n")
app.write("socketio = SocketIO(app, cors_allowed_origins='*')\n")
app.write("\n")
app.write("RULES_PATH = os.path.join(os.path.dirname(__file__), '../rules/rules.json')\n")
app.write("LOGS_PATH = os.path.join(os.path.dirname(__file__), '../logs/firewall.log')\n")
app.write("\n")
app.write("events = []\n")
app.write("\n")
app.write("def load_rules():\n")
app.write("    with open(RULES_PATH) as f:\n")
app.write("        return json.load(f)['rules']\n")
app.write("\n")
app.write("def parse_packet(line):\n")
app.write("    p = {'src_ip': None, 'dst_ip': None, 'protocol': None, 'dst_port': None}\n")
app.write("    if 'ICMP' in line or 'icmp' in line: p['protocol'] = 'ICMP'\n")
app.write("    elif 'Flags' in line: p['protocol'] = 'TCP'\n")
app.write("    elif 'UDP' in line or 'udp' in line: p['protocol'] = 'UDP'\n")
app.write("    m = re.search(r'IP (\\S+) > (\\S+):', line)\n")
app.write("    if m:\n")
app.write("        src, dst = m.group(1), m.group(2)\n")
app.write("        p['src_ip'] = src.rsplit('.', 1)[0]\n")
app.write("        p['dst_ip'] = dst.rsplit('.', 1)[0]\n")
app.write("        pm = re.search(r'\\.(\\d+):', dst)\n")
app.write("        if pm: p['dst_port'] = int(pm.group(1))\n")
app.write("    return p\n")
app.write("\n")
app.write("def evaluate(packet, rules):\n")
app.write("    for rule in rules:\n")
app.write("        if not rule['enabled']: continue\n")
app.write("        if rule['protocol'] and rule['protocol'] != packet['protocol']: continue\n")
app.write("        if rule['src_ip'] and rule['src_ip'] != packet['src_ip']: continue\n")
app.write("        if rule['dst_port'] and rule['dst_port'] != packet['dst_port']: continue\n")
app.write("        return rule['action'], rule['name']\n")
app.write("    return 'ALLOW', 'default'\n")
app.write("\n")
app.write("def capture_traffic():\n")
app.write("    cmd = ['sudo', 'tcpdump', '-i', 'eth0', '-n', '-l', '--immediate-mode', 'ip']\n")
app.write("    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)\n")
app.write("    while True:\n")
app.write("        line = proc.stdout.readline()\n")
app.write("        if not line: break\n")
app.write("        line = line.strip()\n")
app.write("        if not line or 'IP' not in line: continue\n")
app.write("        p = parse_packet(line)\n")
app.write("        if not p['src_ip']: continue\n")
app.write("        alerts = analyze(p['src_ip'], p['dst_port'])\n")
app.write("        action, rule_name = evaluate(p, load_rules())\n")
app.write("        event = {\n")
app.write("            'time': time.strftime('%H:%M:%S'),\n")
app.write("            'action': action,\n")
app.write("            'protocol': p['protocol'],\n")
app.write("            'src': p['src_ip'],\n")
app.write("            'dst': p['dst_ip'],\n")
app.write("            'rule': rule_name,\n")
app.write("            'alerts': alerts\n")
app.write("        }\n")
app.write("        events.append(event)\n")
app.write("        if len(events) > 200: events.pop(0)\n")
app.write("        socketio.emit('packet', event)\n")
app.write("\n")
app.write("@app.route('/')\n")
app.write("def index():\n")
app.write("    return render_template('index.html')\n")
app.write("\n")
app.write("@app.route('/api/events')\n")
app.write("def get_events():\n")
app.write("    return jsonify(events[-50:])\n")
app.write("\n")
app.write("@app.route('/api/rules')\n")
app.write("def get_rules():\n")
app.write("    return jsonify(load_rules())\n")
app.write("\n")
app.write("@app.route('/api/blocked')\n")
app.write("def get_blocked():\n")
app.write("    return jsonify(get_blocked_ips())\n")
app.write("\n")
app.write("@app.route('/api/stats')\n")
app.write("def get_stats():\n")
app.write("    total = len(events)\n")
app.write("    blocked = sum(1 for e in events if e['action'] == 'BLOCK')\n")
app.write("    warnings = sum(1 for e in events if e['alerts'])\n")
app.write("    return jsonify({'total': total, 'blocked': blocked, 'warnings': warnings, 'allowed': total - blocked})\n")
app.write("\n")
app.write("if __name__ == '__main__':\n")
app.write("    t = threading.Thread(target=capture_traffic, daemon=True)\n")
app.write("    t.start()\n")
app.write("    print('Dashboard corriendo en http://0.0.0.0:5000')\n")
app.write("    socketio.run(app, host='0.0.0.0', port=5000, debug=False)\n")
app.close()

html = open(os.path.expanduser("~/firewall/dashboard/templates/index.html"), "w")
html.write("<!DOCTYPE html>\n")
html.write("<html lang='es'>\n")
html.write("<head>\n")
html.write("<meta charset='UTF-8'>\n")
html.write("<meta name='viewport' content='width=device-width, initial-scale=1.0'>\n")
html.write("<title>PyFirewall Dashboard</title>\n")
html.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.7.2/socket.io.min.js'></script>\n")
html.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.umd.min.js'></script>\n")
html.write("<style>\n")
html.write("* { margin:0; padding:0; box-sizing:border-box; }\n")
html.write("body { font-family: monospace; background:#0a0e1a; color:#e0e6f0; }\n")
html.write(".header { background:#111827; border-bottom:1px solid #1e3a5f; padding:16px 24px; display:flex; align-items:center; gap:12px; }\n")
html.write(".header h1 { font-size:18px; color:#38bdf8; }\n")
html.write(".dot { width:8px; height:8px; border-radius:50%; background:#22c55e; animation:pulse 2s infinite; }\n")
html.write("@keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.4} }\n")
html.write(".grid { display:grid; grid-template-columns:repeat(4,1fr); gap:12px; padding:16px 24px; }\n")
html.write(".card { background:#111827; border:1px solid #1e3a5f; border-radius:8px; padding:16px; }\n")
html.write(".card .label { font-size:11px; color:#64748b; margin-bottom:6px; }\n")
html.write(".card .value { font-size:28px; font-weight:bold; }\n")
html.write(".allow { color:#22c55e; } .block { color:#ef4444; } .warn { color:#f59e0b; } .total { color:#38bdf8; }\n")
html.write(".main { display:grid; grid-template-columns:1fr 340px; gap:12px; padding:0 24px 24px; }\n")
html.write(".panel { background:#111827; border:1px solid #1e3a5f; border-radius:8px; padding:16px; }\n")
html.write(".panel h2 { font-size:13px; color:#64748b; margin-bottom:12px; }\n")
html.write(".log-table { width:100%; border-collapse:collapse; font-size:12px; }\n")
html.write(".log-table th { text-align:left; padding:6px 8px; color:#64748b; border-bottom:1px solid #1e3a5f; }\n")
html.write(".log-table td { padding:5px 8px; border-bottom:1px solid #0f172a; }\n")
html.write(".log-table tr:hover { background:#0f172a; }\n")
html.write(".badge { padding:2px 8px; border-radius:4px; font-size:11px; font-weight:bold; }\n")
html.write(".badge-allow { background:#052e16; color:#22c55e; }\n")
html.write(".badge-block { background:#2d0a0a; color:#ef4444; }\n")
html.write(".badge-warn { background:#2d1a00; color:#f59e0b; }\n")
html.write(".rules-list { list-style:none; }\n")
html.write(".rules-list li { padding:8px; border-bottom:1px solid #0f172a; font-size:12px; display:flex; justify-content:space-between; }\n")
html.write(".chart-wrap { height:160px; margin-bottom:16px; }\n")
html.write("#log-body tr { animation: fadeIn 0.3s ease; }\n")
html.write("@keyframes fadeIn { from{opacity:0;transform:translateY(-4px)} to{opacity:1;transform:translateY(0)} }\n")
html.write("</style>\n")
html.write("</head>\n")
html.write("<body>\n")
html.write("<div class='header'>\n")
html.write("  <div class='dot'></div>\n")
html.write("  <h1>PyFirewall Dashboard</h1>\n")
html.write("  <span style='margin-left:auto;font-size:12px;color:#64748b' id='status'>Conectando...</span>\n")
html.write("</div>\n")
html.write("<div class='grid'>\n")
html.write("  <div class='card'><div class='label'>Total paquetes</div><div class='value total' id='total'>0</div></div>\n")
html.write("  <div class='card'><div class='label'>Permitidos</div><div class='value allow' id='allowed'>0</div></div>\n")
html.write("  <div class='card'><div class='label'>Bloqueados</div><div class='value block' id='blocked'>0</div></div>\n")
html.write("  <div class='card'><div class='label'>Alertas</div><div class='value warn' id='warnings'>0</div></div>\n")
html.write("</div>\n")
html.write("<div class='main'>\n")
html.write("  <div class='panel'>\n")
html.write("    <h2>Trafico en tiempo real</h2>\n")
html.write("    <div class='chart-wrap'><canvas id='chart'></canvas></div>\n")
html.write("    <table class='log-table'>\n")
html.write("      <thead><tr><th>Hora</th><th>Accion</th><th>Proto</th><th>Origen</th><th>Destino</th><th>Regla</th></tr></thead>\n")
html.write("      <tbody id='log-body'></tbody>\n")
html.write("    </table>\n")
html.write("  </div>\n")
html.write("  <div style='display:flex;flex-direction:column;gap:12px'>\n")
html.write("    <div class='panel'>\n")
html.write("      <h2>Reglas activas</h2>\n")
html.write("      <ul class='rules-list' id='rules-list'></ul>\n")
html.write("    </div>\n")
html.write("    <div class='panel'>\n")
html.write("      <h2>IPs bloqueadas</h2>\n")
html.write("      <ul class='rules-list' id='blocked-list'></ul>\n")
html.write("    </div>\n")
html.write("  </div>\n")
html.write("</div>\n")
html.write("<script>\n")
html.write("const socket = io();\n")
html.write("let total=0, allowed=0, blocked=0, warnings=0;\n")
html.write("let chartLabels=[], chartAllow=[], chartBlock=[];\n")
html.write("\n")
html.write("const ctx = document.getElementById('chart').getContext('2d');\n")
html.write("const chart = new Chart(ctx, {\n")
html.write("  type: 'line',\n")
html.write("  data: { labels: chartLabels, datasets: [\n")
html.write("    { label: 'Allow', data: chartAllow, borderColor: '#22c55e', backgroundColor: 'rgba(34,197,94,0.1)', tension: 0.4, fill: true },\n")
html.write("    { label: 'Block', data: chartBlock, borderColor: '#ef4444', backgroundColor: 'rgba(239,68,68,0.1)', tension: 0.4, fill: true }\n")
html.write("  ]},\n")
html.write("  options: { responsive:true, maintainAspectRatio:false, plugins:{legend:{labels:{color:'#64748b',font:{size:11}}}}, scales:{ x:{ticks:{color:'#64748b',font:{size:10}},grid:{color:'#0f172a'}}, y:{ticks:{color:'#64748b',font:{size:10}},grid:{color:'#0f172a'}} } }\n")
html.write("});\n")
html.write("\n")
html.write("function addRow(e) {\n")
html.write("  const tbody = document.getElementById('log-body');\n")
html.write("  const tr = document.createElement('tr');\n")
html.write("  const badgeClass = e.action === 'ALLOW' ? 'badge-allow' : 'badge-block';\n")
html.write("  const alertBadge = e.alerts && e.alerts.length ? `<span class='badge badge-warn'>${e.alerts[0]}</span>` : '';\n")
html.write("  tr.innerHTML = `<td>${e.time}</td><td><span class='badge ${badgeClass}'>${e.action}</span>${alertBadge}</td><td>${e.protocol||'?'}</td><td>${e.src}</td><td>${e.dst}</td><td>${e.rule}</td>`;\n")
html.write("  tbody.insertBefore(tr, tbody.firstChild);\n")
html.write("  if (tbody.rows.length > 50) tbody.deleteRow(tbody.rows.length-1);\n")
html.write("}\n")
html.write("\n")
html.write("function updateStats() {\n")
html.write("  document.getElementById('total').textContent = total;\n")
html.write("  document.getElementById('allowed').textContent = allowed;\n")
html.write("  document.getElementById('blocked').textContent = blocked;\n")
html.write("  document.getElementById('warnings').textContent = warnings;\n")
html.write("}\n")
html.write("\n")
html.write("function updateChart(action) {\n")
html.write("  const t = new Date().toLocaleTimeString('es',{hour:'2-digit',minute:'2-digit',second:'2-digit'});\n")
html.write("  if (chartLabels.length === 0 || chartLabels[chartLabels.length-1] !== t) {\n")
html.write("    chartLabels.push(t); chartAllow.push(0); chartBlock.push(0);\n")
html.write("    if (chartLabels.length > 20) { chartLabels.shift(); chartAllow.shift(); chartBlock.shift(); }\n")
html.write("  }\n")
html.write("  if (action === 'ALLOW') chartAllow[chartAllow.length-1]++;\n")
html.write("  else chartBlock[chartBlock.length-1]++;\n")
html.write("  chart.update('none');\n")
html.write("}\n")
html.write("\n")
html.write("socket.on('connect', () => { document.getElementById('status').textContent = 'En vivo'; });\n")
html.write("socket.on('disconnect', () => { document.getElementById('status').textContent = 'Desconectado'; });\n")
html.write("\n")
html.write("socket.on('packet', (e) => {\n")
html.write("  total++;\n")
html.write("  if (e.action === 'ALLOW') allowed++; else blocked++;\n")
html.write("  if (e.alerts && e.alerts.length) warnings++;\n")
html.write("  updateStats();\n")
html.write("  addRow(e);\n")
html.write("  updateChart(e.action);\n")
html.write("});\n")
html.write("\n")
html.write("function loadRules() {\n")
html.write("  fetch('/api/rules').then(r=>r.json()).then(rules => {\n")
html.write("    const ul = document.getElementById('rules-list');\n")
html.write("    ul.innerHTML = rules.map(r => `<li><span>${r.name}</span><span class='badge ${r.action==='ALLOW'?'badge-allow':'badge-block'}'>${r.action}</span></li>`).join('');\n")
html.write("  });\n")
html.write("}\n")
html.write("\n")
html.write("function loadBlocked() {\n")
html.write("  fetch('/api/blocked').then(r=>r.json()).then(ips => {\n")
html.write("    const ul = document.getElementById('blocked-list');\n")
html.write("    ul.innerHTML = ips.length ? ips.map(ip => `<li><span>${ip}</span><span class='badge badge-block'>BLOCKED</span></li>`).join('') : '<li style=\"color:#64748b\">Ninguna IP bloqueada</li>';\n")
html.write("  });\n")
html.write("}\n")
html.write("\n")
html.write("loadRules();\n")
html.write("loadBlocked();\n")
html.write("setInterval(loadBlocked, 5000);\n")
html.write("</script>\n")
html.write("</body>\n")
html.write("</html>\n")
html.close()

print("Dashboard creado OK")
PYEOF
