#!/bin/bash
python3 - << 'PYEOF'
import os

os.makedirs(os.path.expanduser("~/firewall/db"), exist_ok=True)

db = open(os.path.expanduser("~/firewall/core/database.py"), "w")
db.write("#!/usr/bin/env python3\n")
db.write("import sqlite3, os, time\n")
db.write("\n")
db.write("DB_PATH = os.path.join(os.path.dirname(__file__), '../db/firewall.db')\n")
db.write("\n")
db.write("def get_conn():\n")
db.write("    conn = sqlite3.connect(DB_PATH)\n")
db.write("    conn.row_factory = sqlite3.Row\n")
db.write("    return conn\n")
db.write("\n")
db.write("def init_db():\n")
db.write("    conn = get_conn()\n")
db.write("    conn.execute('''\n")
db.write("        CREATE TABLE IF NOT EXISTS events (\n")
db.write("            id INTEGER PRIMARY KEY AUTOINCREMENT,\n")
db.write("            timestamp TEXT,\n")
db.write("            action TEXT,\n")
db.write("            protocol TEXT,\n")
db.write("            src_ip TEXT,\n")
db.write("            dst_ip TEXT,\n")
db.write("            rule TEXT,\n")
db.write("            alerts TEXT\n")
db.write("        )\n")
db.write("    ''')\n")
db.write("    conn.execute('''\n")
db.write("        CREATE TABLE IF NOT EXISTS alerts (\n")
db.write("            id INTEGER PRIMARY KEY AUTOINCREMENT,\n")
db.write("            timestamp TEXT,\n")
db.write("            src_ip TEXT,\n")
db.write("            alert_type TEXT,\n")
db.write("            details TEXT\n")
db.write("        )\n")
db.write("    ''')\n")
db.write("    conn.commit()\n")
db.write("    conn.close()\n")
db.write("\n")
db.write("def save_event(action, protocol, src_ip, dst_ip, rule, alerts):\n")
db.write("    try:\n")
db.write("        conn = get_conn()\n")
db.write("        conn.execute(\n")
db.write("            'INSERT INTO events (timestamp, action, protocol, src_ip, dst_ip, rule, alerts) VALUES (?,?,?,?,?,?,?)',\n")
db.write("            (time.strftime('%Y-%m-%d %H:%M:%S'), action, protocol, src_ip, dst_ip, rule, ','.join(alerts))\n")
db.write("        )\n")
db.write("        conn.commit()\n")
db.write("        conn.close()\n")
db.write("    except Exception as e:\n")
db.write("        pass\n")
db.write("\n")
db.write("def save_alert(src_ip, alert_type, details):\n")
db.write("    try:\n")
db.write("        conn = get_conn()\n")
db.write("        conn.execute(\n")
db.write("            'INSERT INTO alerts (timestamp, src_ip, alert_type, details) VALUES (?,?,?,?)',\n")
db.write("            (time.strftime('%Y-%m-%d %H:%M:%S'), src_ip, alert_type, details)\n")
db.write("        )\n")
db.write("        conn.commit()\n")
db.write("        conn.close()\n")
db.write("    except Exception as e:\n")
db.write("        pass\n")
db.write("\n")
db.write("def get_recent_events(limit=100):\n")
db.write("    conn = get_conn()\n")
db.write("    rows = conn.execute(\n")
db.write("        'SELECT * FROM events ORDER BY id DESC LIMIT ?', (limit,)\n")
db.write("    ).fetchall()\n")
db.write("    conn.close()\n")
db.write("    return [dict(r) for r in rows]\n")
db.write("\n")
db.write("def get_recent_alerts(limit=50):\n")
db.write("    conn = get_conn()\n")
db.write("    rows = conn.execute(\n")
db.write("        'SELECT * FROM alerts ORDER BY id DESC LIMIT ?', (limit,)\n")
db.write("    ).fetchall()\n")
db.write("    conn.close()\n")
db.write("    return [dict(r) for r in rows]\n")
db.write("\n")
db.write("def get_stats():\n")
db.write("    conn = get_conn()\n")
db.write("    total = conn.execute('SELECT COUNT(*) FROM events').fetchone()[0]\n")
db.write("    blocked = conn.execute('SELECT COUNT(*) FROM events WHERE action=\"BLOCK\"').fetchone()[0]\n")
db.write("    alerts = conn.execute('SELECT COUNT(*) FROM alerts').fetchone()[0]\n")
db.write("    conn.close()\n")
db.write("    return {'total': total, 'blocked': blocked, 'alerts': alerts, 'allowed': total - blocked}\n")
db.close()

print("database.py creado OK")
PYEOF
