#!/bin/bash
python3 - << 'PYEOF'
import json, os

rules = {"rules": [{"id": 1, "name": "Block Telnet", "action": "BLOCK", "protocol": "TCP", "src_ip": None, "dst_port": 23, "enabled": True}, {"id": 2, "name": "Allow all", "action": "ALLOW", "protocol": None, "src_ip": None, "dst_port": None, "enabled": True}]}

with open(os.path.expanduser("~/firewall/rules/rules.json"), "w") as f:
    json.dump(rules, f, indent=2)

engine = open(os.path.expanduser("~/firewall/core/engine_v2.py"), "w")
engine.write("#!/usr/bin/env python3\n")
engine.write("import subprocess, json, logging, os, re\n")
engine.write("\n")
engine.write("RULES_PATH = os.path.join(os.path.dirname(__file__), '../rules/rules.json')\n")
engine.write("LOGS_PATH = os.path.join(os.path.dirname(__file__), '../logs/firewall.log')\n")
engine.write("\n")
engine.write("logging.basicConfig(filename=LOGS_PATH, level=logging.INFO, format='%(asctime)s %(message)s')\n")
engine.write("\n")
engine.write("def load_rules():\n")
engine.write("    with open(RULES_PATH) as f:\n")
engine.write("        return json.load(f)['rules']\n")
engine.write("\n")
engine.write("def parse_packet(line):\n")
engine.write("    p = {'src_ip': None, 'dst_ip': None, 'protocol': None, 'dst_port': None}\n")
engine.write("    if 'ICMP' in line or 'icmp' in line: p['protocol'] = 'ICMP'\n")
engine.write("    elif 'Flags' in line: p['protocol'] = 'TCP'\n")
engine.write("    elif 'UDP' in line or 'udp' in line: p['protocol'] = 'UDP'\n")
engine.write("    m = re.search(r'IP (\\S+) > (\\S+):', line)\n")
engine.write("    if m:\n")
engine.write("        src, dst = m.group(1), m.group(2)\n")
engine.write("        p['src_ip'] = src.rsplit('.', 1)[0]\n")
engine.write("        p['dst_ip'] = dst.rsplit('.', 1)[0]\n")
engine.write("        pm = re.search(r'\\.(\\d+):', dst)\n")
engine.write("        if pm: p['dst_port'] = int(pm.group(1))\n")
engine.write("    return p\n")
engine.write("\n")
engine.write("def evaluate(packet, rules):\n")
engine.write("    for rule in rules:\n")
engine.write("        if not rule['enabled']: continue\n")
engine.write("        if rule['protocol'] and rule['protocol'] != packet['protocol']: continue\n")
engine.write("        if rule['src_ip'] and rule['src_ip'] != packet['src_ip']: continue\n")
engine.write("        if rule['dst_port'] and rule['dst_port'] != packet['dst_port']: continue\n")
engine.write("        return rule['action'], rule['name']\n")
engine.write("    return 'ALLOW', 'default'\n")
engine.write("\n")
engine.write("def process_line(line, rules):\n")
engine.write("    line = line.strip()\n")
engine.write("    if not line or 'IP' not in line: return\n")
engine.write("    p = parse_packet(line)\n")
engine.write("    if not p['src_ip']: return\n")
engine.write("    action, rule_name = evaluate(p, rules)\n")
engine.write("    msg = f\"[{action}] {p['protocol']} {p['src_ip']} -> {p['dst_ip']} | rule: {rule_name}\"\n")
engine.write("    print(msg)\n")
engine.write("    logging.info(msg)\n")
engine.write("\n")
engine.write("if __name__ == '__main__':\n")
engine.write("    print('Firewall iniciado. Capturando trafico en eth0... (Ctrl+C para parar)')\n")
engine.write("    cmd = ['sudo', 'tcpdump', '-i', 'eth0', '-n', '-l', '--immediate-mode', 'ip']\n")
engine.write("    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)\n")
engine.write("    try:\n")
engine.write("        while True:\n")
engine.write("            line = proc.stdout.readline()\n")
engine.write("            if not line: break\n")
engine.write("            process_line(line, load_rules())\n")
engine.write("    except KeyboardInterrupt:\n")
engine.write("        proc.terminate()\n")
engine.write("        print('\\nFirewall detenido.')\n")
engine.close()

print("Ficheros creados OK")
PYEOF
