#!/bin/bash
python3 - << 'PYEOF'
import os

app = open(os.path.expanduser("~/firewall/dashboard/app.py"), "w")
app.write("#!/usr/bin/env python3\n")
app.write("from flask import Flask, render_template, jsonify\n")
app.write("from flask_socketio import SocketIO\n")
app.write("import json, os, threading, subprocess, re, time\n")
app.write("import sys\n")
app.write("sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../core'))\n")
app.write("from detector import analyze, get_blocked_ips\n")
app.write("from ai_analyzer import analyze_async\n")
app.write("\n")
app.write("app = Flask(__name__)\n")
app.write("socketio = SocketIO(app, cors_allowed_origins='*')\n")
app.write("\n")
app.write("RULES_PATH = os.path.join(os.path.dirname(__file__), '../rules/rules.json')\n")
app.write("LOGS_PATH = os.path.join(os.path.dirname(__file__), '../logs/firewall.log')\n")
app.write("\n")
app.write("events = []\n")
app.write("ai_analyses = []\n")
app.write("\n")
app.write("def load_rules():\n")
app.write("    with open(RULES_PATH) as f:\n")
app.write("        return json.load(f)['rules']\n")
app.write("\n")
app.write("def parse_packet(line):\n")
app.write("    p = {'src_ip': None, 'dst_ip': None, 'protocol': None, 'dst_port': None}\n")
app.write("    if 'ICMP' in line or 'icmp' in line: p['protocol'] = 'ICMP'\n")
app.write("    elif 'Flags' in line: p['protocol'] = 'TCP'\n")
app.write("    elif 'UDP' in line or 'udp' in line: p['protocol'] = 'UDP'\n")
app.write("    m = re.search(r'IP (\\S+) > (\\S+):', line)\n")
app.write("    if m:\n")
app.write("        src, dst = m.group(1), m.group(2)\n")
app.write("        p['src_ip'] = src.rsplit('.', 1)[0]\n")
app.write("        p['dst_ip'] = dst.rsplit('.', 1)[0]\n")
app.write("        pm = re.search(r'\\.(\\d+):', dst)\n")
app.write("        if pm: p['dst_port'] = int(pm.group(1))\n")
app.write("    return p\n")
app.write("\n")
app.write("def evaluate(packet, rules):\n")
app.write("    for rule in rules:\n")
app.write("        if not rule['enabled']: continue\n")
app.write("        if rule['protocol'] and rule['protocol'] != packet['protocol']: continue\n")
app.write("        if rule['src_ip'] and rule['src_ip'] != packet['src_ip']: continue\n")
app.write("        if rule['dst_port'] and rule['dst_port'] != packet['dst_port']: continue\n")
app.write("        return rule['action'], rule['name']\n")
app.write("    return 'ALLOW', 'default'\n")
app.write("\n")
app.write("def on_ai_result(src_ip, alert_type, result):\n")
app.write("    analysis = {\n")
app.write("        'time': time.strftime('%H:%M:%S'),\n")
app.write("        'src_ip': src_ip,\n")
app.write("        'alert_type': alert_type,\n")
app.write("        'analysis': result\n")
app.write("    }\n")
app.write("    ai_analyses.append(analysis)\n")
app.write("    if len(ai_analyses) > 20: ai_analyses.pop(0)\n")
app.write("    socketio.emit('ai_analysis', analysis)\n")
app.write("\n")
app.write("def capture_traffic():\n")
app.write("    cmd = ['sudo', 'tcpdump', '-i', 'eth0', '-n', '-l', '--immediate-mode', 'ip']\n")
app.write("    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)\n")
app.write("    while True:\n")
app.write("        line = proc.stdout.readline()\n")
app.write("        if not line: break\n")
app.write("        line = line.strip()\n")
app.write("        if not line or 'IP' not in line: continue\n")
app.write("        p = parse_packet(line)\n")
app.write("        if not p['src_ip']: continue\n")
app.write("        alerts = analyze(p['src_ip'], p['dst_port'])\n")
app.write("        action, rule_name = evaluate(p, load_rules())\n")
app.write("        event = {\n")
app.write("            'time': time.strftime('%H:%M:%S'),\n")
app.write("            'action': action,\n")
app.write("            'protocol': p['protocol'],\n")
app.write("            'src': p['src_ip'],\n")
app.write("            'dst': p['dst_ip'],\n")
app.write("            'rule': rule_name,\n")
app.write("            'alerts': alerts\n")
app.write("        }\n")
app.write("        events.append(event)\n")
app.write("        if len(events) > 200: events.pop(0)\n")
app.write("        socketio.emit('packet', event)\n")
app.write("        if alerts:\n")
app.write("            details = f'Puertos escaneados: {p[\"dst_port\"]}' if 'PORT_SCAN' in alerts else f'Paquetes en ventana de tiempo excedidos'\n")
app.write("            analyze_async(p['src_ip'], alerts[0], details, lambda r, ip=p['src_ip'], a=alerts[0]: on_ai_result(ip, a, r))\n")
app.write("\n")
app.write("@app.route('/')\n")
app.write("def index():\n")
app.write("    return render_template('index.html')\n")
app.write("\n")
app.write("@app.route('/api/events')\n")
app.write("def get_events():\n")
app.write("    return jsonify(events[-50:])\n")
app.write("\n")
app.write("@app.route('/api/rules')\n")
app.write("def get_rules():\n")
app.write("    return jsonify(load_rules())\n")
app.write("\n")
app.write("@app.route('/api/blocked')\n")
app.write("def get_blocked():\n")
app.write("    return jsonify(get_blocked_ips())\n")
app.write("\n")
app.write("@app.route('/api/ai')\n")
app.write("def get_ai():\n")
app.write("    return jsonify(ai_analyses)\n")
app.write("\n")
app.write("@app.route('/api/stats')\n")
app.write("def get_stats():\n")
app.write("    total = len(events)\n")
app.write("    blocked = sum(1 for e in events if e['action'] == 'BLOCK')\n")
app.write("    warnings = sum(1 for e in events if e['alerts'])\n")
app.write("    return jsonify({'total': total, 'blocked': blocked, 'warnings': warnings, 'allowed': total - blocked})\n")
app.write("\n")
app.write("if __name__ == '__main__':\n")
app.write("    t = threading.Thread(target=capture_traffic, daemon=True)\n")
app.write("    t.start()\n")
app.write("    print('Dashboard corriendo en http://0.0.0.0:5000')\n")
app.write("    socketio.run(app, host='0.0.0.0', port=5000, debug=False)\n")
app.close()

print("app.py actualizado OK")
PYEOF
