#!/bin/bash
python3 - << 'PYEOF'
import os

html = open(os.path.expanduser("~/firewall/dashboard/templates/index.html"), "w")
html.write("<!DOCTYPE html>\n")
html.write("<html lang='es'>\n")
html.write("<head>\n")
html.write("<meta charset='UTF-8'>\n")
html.write("<meta name='viewport' content='width=device-width, initial-scale=1.0'>\n")
html.write("<title>PyFirewall Dashboard</title>\n")
html.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.7.2/socket.io.min.js'></script>\n")
html.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.umd.min.js'></script>\n")
html.write("<style>\n")
html.write("* { margin:0; padding:0; box-sizing:border-box; }\n")
html.write("body { font-family: monospace; background:#0a0e1a; color:#e0e6f0; }\n")
html.write(".header { background:#111827; border-bottom:1px solid #1e3a5f; padding:16px 24px; display:flex; align-items:center; gap:12px; }\n")
html.write(".header h1 { font-size:18px; color:#38bdf8; }\n")
html.write(".dot { width:8px; height:8px; border-radius:50%; background:#22c55e; animation:pulse 2s infinite; }\n")
html.write("@keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.4} }\n")
html.write(".grid { display:grid; grid-template-columns:repeat(4,1fr); gap:12px; padding:16px 24px; }\n")
html.write(".card { background:#111827; border:1px solid #1e3a5f; border-radius:8px; padding:16px; }\n")
html.write(".card .label { font-size:11px; color:#64748b; margin-bottom:6px; }\n")
html.write(".card .value { font-size:28px; font-weight:bold; }\n")
html.write(".allow { color:#22c55e; } .block { color:#ef4444; } .warn { color:#f59e0b; } .total { color:#38bdf8; }\n")
html.write(".main { display:grid; grid-template-columns:1fr 340px; gap:12px; padding:0 24px 24px; }\n")
html.write(".panel { background:#111827; border:1px solid #1e3a5f; border-radius:8px; padding:16px; }\n")
html.write(".panel h2 { font-size:13px; color:#64748b; margin-bottom:12px; }\n")
html.write(".log-table { width:100%; border-collapse:collapse; font-size:12px; }\n")
html.write(".log-table th { text-align:left; padding:6px 8px; color:#64748b; border-bottom:1px solid #1e3a5f; }\n")
html.write(".log-table td { padding:5px 8px; border-bottom:1px solid #0f172a; }\n")
html.write(".log-table tr:hover { background:#0f172a; }\n")
html.write(".badge { padding:2px 8px; border-radius:4px; font-size:11px; font-weight:bold; }\n")
html.write(".badge-allow { background:#052e16; color:#22c55e; }\n")
html.write(".badge-block { background:#2d0a0a; color:#ef4444; }\n")
html.write(".badge-warn { background:#2d1a00; color:#f59e0b; }\n")
html.write(".badge-ai { background:#1a1a3a; color:#a78bfa; }\n")
html.write(".rules-list { list-style:none; }\n")
html.write(".rules-list li { padding:8px; border-bottom:1px solid #0f172a; font-size:12px; display:flex; justify-content:space-between; align-items:center; }\n")
html.write(".chart-wrap { height:160px; margin-bottom:16px; }\n")
html.write(".ai-card { background:#0f0f2a; border:1px solid #2d2d6b; border-radius:8px; padding:12px; margin-bottom:8px; font-size:12px; }\n")
html.write(".ai-card .ai-header { display:flex; justify-content:space-between; margin-bottom:6px; }\n")
html.write(".ai-card .ai-ip { color:#a78bfa; font-weight:bold; }\n")
html.write(".ai-card .ai-type { color:#f59e0b; font-size:11px; }\n")
html.write(".ai-card .ai-text { color:#cbd5e1; line-height:1.5; }\n")
html.write(".ai-card .ai-time { color:#475569; font-size:10px; }\n")
html.write(".ai-thinking { color:#64748b; font-size:12px; font-style:italic; padding:8px; }\n")
html.write("#ai-panel { max-height:400px; overflow-y:auto; }\n")
html.write("@keyframes fadeIn { from{opacity:0;transform:translateY(-4px)} to{opacity:1;transform:translateY(0)} }\n")
html.write(".fadeIn { animation: fadeIn 0.3s ease; }\n")
html.write("</style>\n")
html.write("</head>\n")
html.write("<body>\n")
html.write("<div class='header'>\n")
html.write("  <div class='dot'></div>\n")
html.write("  <h1>PyFirewall Dashboard</h1>\n")
html.write("  <span style='margin-left:8px;font-size:11px;color:#a78bfa'>+ AI Analysis</span>\n")
html.write("  <span style='margin-left:auto;font-size:12px;color:#64748b' id='status'>Conectando...</span>\n")
html.write("</div>\n")
html.write("<div class='grid'>\n")
html.write("  <div class='card'><div class='label'>Total paquetes</div><div class='value total' id='total'>0</div></div>\n")
html.write("  <div class='card'><div class='label'>Permitidos</div><div class='value allow' id='allowed'>0</div></div>\n")
html.write("  <div class='card'><div class='label'>Bloqueados</div><div class='value block' id='blocked'>0</div></div>\n")
html.write("  <div class='card'><div class='label'>Alertas IA</div><div class='value warn' id='warnings'>0</div></div>\n")
html.write("</div>\n")
html.write("<div class='main'>\n")
html.write("  <div style='display:flex;flex-direction:column;gap:12px'>\n")
html.write("    <div class='panel'>\n")
html.write("      <h2>Trafico en tiempo real</h2>\n")
html.write("      <div class='chart-wrap'><canvas id='chart'></canvas></div>\n")
html.write("      <table class='log-table'>\n")
html.write("        <thead><tr><th>Hora</th><th>Accion</th><th>Proto</th><th>Origen</th><th>Destino</th><th>Regla</th></tr></thead>\n")
html.write("        <tbody id='log-body'></tbody>\n")
html.write("      </table>\n")
html.write("    </div>\n")
html.write("    <div class='panel'>\n")
html.write("      <h2>Analisis IA <span class='badge badge-ai'>Claude</span></h2>\n")
html.write("      <div id='ai-panel'><p class='ai-thinking'>Esperando alertas para analizar...</p></div>\n")
html.write("    </div>\n")
html.write("  </div>\n")
html.write("  <div style='display:flex;flex-direction:column;gap:12px'>\n")
html.write("    <div class='panel'>\n")
html.write("      <h2>Reglas activas</h2>\n")
html.write("      <ul class='rules-list' id='rules-list'></ul>\n")
html.write("    </div>\n")
html.write("    <div class='panel'>\n")
html.write("      <h2>IPs bloqueadas</h2>\n")
html.write("      <ul class='rules-list' id='blocked-list'></ul>\n")
html.write("    </div>\n")
html.write("  </div>\n")
html.write("</div>\n")
html.write("<script>\n")
html.write("const socket = io();\n")
html.write("let total=0, allowed=0, blocked=0, warnings=0;\n")
html.write("let chartLabels=[], chartAllow=[], chartBlock=[];\n")
html.write("\n")
html.write("const ctx = document.getElementById('chart').getContext('2d');\n")
html.write("const chart = new Chart(ctx, {\n")
html.write("  type: 'line',\n")
html.write("  data: { labels: chartLabels, datasets: [\n")
html.write("    { label: 'Allow', data: chartAllow, borderColor: '#22c55e', backgroundColor: 'rgba(34,197,94,0.1)', tension: 0.4, fill: true },\n")
html.write("    { label: 'Block', data: chartBlock, borderColor: '#ef4444', backgroundColor: 'rgba(239,68,68,0.1)', tension: 0.4, fill: true }\n")
html.write("  ]},\n")
html.write("  options: { responsive:true, maintainAspectRatio:false, plugins:{legend:{labels:{color:'#64748b',font:{size:11}}}}, scales:{ x:{ticks:{color:'#64748b',font:{size:10}},grid:{color:'#0f172a'}}, y:{ticks:{color:'#64748b',font:{size:10}},grid:{color:'#0f172a'}} } }\n")
html.write("});\n")
html.write("\n")
html.write("function addRow(e) {\n")
html.write("  const tbody = document.getElementById('log-body');\n")
html.write("  const tr = document.createElement('tr');\n")
html.write("  tr.className = 'fadeIn';\n")
html.write("  const badgeClass = e.action === 'ALLOW' ? 'badge-allow' : 'badge-block';\n")
html.write("  const alertBadge = e.alerts && e.alerts.length ? `<span class='badge badge-warn' style='margin-left:4px'>${e.alerts[0]}</span>` : '';\n")
html.write("  tr.innerHTML = `<td>${e.time}</td><td><span class='badge ${badgeClass}'>${e.action}</span>${alertBadge}</td><td>${e.protocol||'?'}</td><td>${e.src}</td><td>${e.dst}</td><td>${e.rule}</td>`;\n")
html.write("  tbody.insertBefore(tr, tbody.firstChild);\n")
html.write("  if (tbody.rows.length > 50) tbody.deleteRow(tbody.rows.length-1);\n")
html.write("}\n")
html.write("\n")
html.write("function addAiCard(a) {\n")
html.write("  const panel = document.getElementById('ai-panel');\n")
html.write("  const placeholder = panel.querySelector('.ai-thinking');\n")
html.write("  if (placeholder) placeholder.remove();\n")
html.write("  const div = document.createElement('div');\n")
html.write("  div.className = 'ai-card fadeIn';\n")
html.write("  div.innerHTML = `\n")
html.write("    <div class='ai-header'>\n")
html.write("      <span class='ai-ip'>${a.src_ip}</span>\n")
html.write("      <span class='ai-type'>${a.alert_type}</span>\n")
html.write("      <span class='ai-time'>${a.time}</span>\n")
html.write("    </div>\n")
html.write("    <div class='ai-text'>${a.analysis}</div>\n")
html.write("  `;\n")
html.write("  panel.insertBefore(div, panel.firstChild);\n")
html.write("  warnings++;\n")
html.write("  document.getElementById('warnings').textContent = warnings;\n")
html.write("}\n")
html.write("\n")
html.write("function updateStats() {\n")
html.write("  document.getElementById('total').textContent = total;\n")
html.write("  document.getElementById('allowed').textContent = allowed;\n")
html.write("  document.getElementById('blocked').textContent = blocked;\n")
html.write("}\n")
html.write("\n")
html.write("function updateChart(action) {\n")
html.write("  const t = new Date().toLocaleTimeString('es',{hour:'2-digit',minute:'2-digit',second:'2-digit'});\n")
html.write("  if (chartLabels.length === 0 || chartLabels[chartLabels.length-1] !== t) {\n")
html.write("    chartLabels.push(t); chartAllow.push(0); chartBlock.push(0);\n")
html.write("    if (chartLabels.length > 20) { chartLabels.shift(); chartAllow.shift(); chartBlock.shift(); }\n")
html.write("  }\n")
html.write("  if (action === 'ALLOW') chartAllow[chartAllow.length-1]++;\n")
html.write("  else chartBlock[chartBlock.length-1]++;\n")
html.write("  chart.update('none');\n")
html.write("}\n")
html.write("\n")
html.write("socket.on('connect', () => { document.getElementById('status').textContent = 'En vivo'; });\n")
html.write("socket.on('disconnect', () => { document.getElementById('status').textContent = 'Desconectado'; });\n")
html.write("\n")
html.write("socket.on('packet', (e) => {\n")
html.write("  total++;\n")
html.write("  if (e.action === 'ALLOW') allowed++; else blocked++;\n")
html.write("  updateStats();\n")
html.write("  addRow(e);\n")
html.write("  updateChart(e.action);\n")
html.write("});\n")
html.write("\n")
html.write("socket.on('ai_analysis', (a) => {\n")
html.write("  addAiCard(a);\n")
html.write("});\n")
html.write("\n")
html.write("function loadRules() {\n")
html.write("  fetch('/api/rules').then(r=>r.json()).then(rules => {\n")
html.write("    const ul = document.getElementById('rules-list');\n")
html.write("    ul.innerHTML = rules.map(r => `<li><span>${r.name}</span><span class='badge ${r.action===\"ALLOW\"?\"badge-allow\":\"badge-block\"}'>${r.action}</span></li>`).join('');\n")
html.write("  });\n")
html.write("}\n")
html.write("\n")
html.write("function loadBlocked() {\n")
html.write("  fetch('/api/blocked').then(r=>r.json()).then(ips => {\n")
html.write("    const ul = document.getElementById('blocked-list');\n")
html.write("    ul.innerHTML = ips.length ? ips.map(ip => `<li><span>${ip}</span><span class='badge badge-block'>BLOCKED</span></li>`).join('') : '<li style=\"color:#64748b\">Ninguna IP bloqueada</li>';\n")
html.write("  });\n")
html.write("}\n")
html.write("\n")
html.write("loadRules();\n")
html.write("loadBlocked();\n")
html.write("setInterval(loadBlocked, 5000);\n")
html.write("</script>\n")
html.write("</body>\n")
html.write("</html>\n")
html.close()

print("index.html actualizado OK")
PYEOF
